<?php

namespace AppBundle\Repository;

/**
 * HospedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospedeRepository extends \Doctrine\ORM\EntityRepository
{
}
